#!/usr/bin/env sh

# docker compose by default will sync non-existing node_modules directory on first run
if [ ! -d "node_modules" ] || [ -z "$(ls -A node_modules 2>/dev/null)" ]; then
    echo "node_modules directory is missing or empty, recreating..."
    npm install # install dependencies
fi

npx prisma generate # generate database schema
npm run database:migrate # execute database schema migrations
npm run database:seed # load example data to database
npm run start:dev # start app in dev mode
