
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CompletionStep` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CompletionStep
 * 
 */
export type CompletionStepModel = runtime.Types.Result.DefaultSelection<Prisma.$CompletionStepPayload>

export type AggregateCompletionStep = {
  _count: CompletionStepCountAggregateOutputType | null
  _min: CompletionStepMinAggregateOutputType | null
  _max: CompletionStepMaxAggregateOutputType | null
}

export type CompletionStepMinAggregateOutputType = {
  id: string | null
  description: string | null
  status: boolean | null
  achievementId: string | null
}

export type CompletionStepMaxAggregateOutputType = {
  id: string | null
  description: string | null
  status: boolean | null
  achievementId: string | null
}

export type CompletionStepCountAggregateOutputType = {
  id: number
  description: number
  status: number
  achievementId: number
  _all: number
}


export type CompletionStepMinAggregateInputType = {
  id?: true
  description?: true
  status?: true
  achievementId?: true
}

export type CompletionStepMaxAggregateInputType = {
  id?: true
  description?: true
  status?: true
  achievementId?: true
}

export type CompletionStepCountAggregateInputType = {
  id?: true
  description?: true
  status?: true
  achievementId?: true
  _all?: true
}

export type CompletionStepAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CompletionStep to aggregate.
   */
  where?: Prisma.CompletionStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CompletionSteps to fetch.
   */
  orderBy?: Prisma.CompletionStepOrderByWithRelationInput | Prisma.CompletionStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CompletionStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CompletionSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CompletionSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CompletionSteps
  **/
  _count?: true | CompletionStepCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CompletionStepMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CompletionStepMaxAggregateInputType
}

export type GetCompletionStepAggregateType<T extends CompletionStepAggregateArgs> = {
      [P in keyof T & keyof AggregateCompletionStep]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCompletionStep[P]>
    : Prisma.GetScalarType<T[P], AggregateCompletionStep[P]>
}




export type CompletionStepGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CompletionStepWhereInput
  orderBy?: Prisma.CompletionStepOrderByWithAggregationInput | Prisma.CompletionStepOrderByWithAggregationInput[]
  by: Prisma.CompletionStepScalarFieldEnum[] | Prisma.CompletionStepScalarFieldEnum
  having?: Prisma.CompletionStepScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CompletionStepCountAggregateInputType | true
  _min?: CompletionStepMinAggregateInputType
  _max?: CompletionStepMaxAggregateInputType
}

export type CompletionStepGroupByOutputType = {
  id: string
  description: string | null
  status: boolean
  achievementId: string
  _count: CompletionStepCountAggregateOutputType | null
  _min: CompletionStepMinAggregateOutputType | null
  _max: CompletionStepMaxAggregateOutputType | null
}

type GetCompletionStepGroupByPayload<T extends CompletionStepGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CompletionStepGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CompletionStepGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CompletionStepGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CompletionStepGroupByOutputType[P]>
      }
    >
  >



export type CompletionStepWhereInput = {
  AND?: Prisma.CompletionStepWhereInput | Prisma.CompletionStepWhereInput[]
  OR?: Prisma.CompletionStepWhereInput[]
  NOT?: Prisma.CompletionStepWhereInput | Prisma.CompletionStepWhereInput[]
  id?: Prisma.StringFilter<"CompletionStep"> | string
  description?: Prisma.StringNullableFilter<"CompletionStep"> | string | null
  status?: Prisma.BoolFilter<"CompletionStep"> | boolean
  achievementId?: Prisma.StringFilter<"CompletionStep"> | string
  achievement?: Prisma.XOR<Prisma.AchievementScalarRelationFilter, Prisma.AchievementWhereInput>
}

export type CompletionStepOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  achievementId?: Prisma.SortOrder
  achievement?: Prisma.AchievementOrderByWithRelationInput
}

export type CompletionStepWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CompletionStepWhereInput | Prisma.CompletionStepWhereInput[]
  OR?: Prisma.CompletionStepWhereInput[]
  NOT?: Prisma.CompletionStepWhereInput | Prisma.CompletionStepWhereInput[]
  description?: Prisma.StringNullableFilter<"CompletionStep"> | string | null
  status?: Prisma.BoolFilter<"CompletionStep"> | boolean
  achievementId?: Prisma.StringFilter<"CompletionStep"> | string
  achievement?: Prisma.XOR<Prisma.AchievementScalarRelationFilter, Prisma.AchievementWhereInput>
}, "id">

export type CompletionStepOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  achievementId?: Prisma.SortOrder
  _count?: Prisma.CompletionStepCountOrderByAggregateInput
  _max?: Prisma.CompletionStepMaxOrderByAggregateInput
  _min?: Prisma.CompletionStepMinOrderByAggregateInput
}

export type CompletionStepScalarWhereWithAggregatesInput = {
  AND?: Prisma.CompletionStepScalarWhereWithAggregatesInput | Prisma.CompletionStepScalarWhereWithAggregatesInput[]
  OR?: Prisma.CompletionStepScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CompletionStepScalarWhereWithAggregatesInput | Prisma.CompletionStepScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CompletionStep"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"CompletionStep"> | string | null
  status?: Prisma.BoolWithAggregatesFilter<"CompletionStep"> | boolean
  achievementId?: Prisma.StringWithAggregatesFilter<"CompletionStep"> | string
}

export type CompletionStepCreateInput = {
  id?: string
  description?: string | null
  status: boolean
  achievement: Prisma.AchievementCreateNestedOneWithoutCompletionStepsInput
}

export type CompletionStepUncheckedCreateInput = {
  id?: string
  description?: string | null
  status: boolean
  achievementId: string
}

export type CompletionStepUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievement?: Prisma.AchievementUpdateOneRequiredWithoutCompletionStepsNestedInput
}

export type CompletionStepUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievementId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CompletionStepCreateManyInput = {
  id?: string
  description?: string | null
  status: boolean
  achievementId: string
}

export type CompletionStepUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CompletionStepUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievementId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CompletionStepListRelationFilter = {
  every?: Prisma.CompletionStepWhereInput
  some?: Prisma.CompletionStepWhereInput
  none?: Prisma.CompletionStepWhereInput
}

export type CompletionStepOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CompletionStepCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  achievementId?: Prisma.SortOrder
}

export type CompletionStepMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  achievementId?: Prisma.SortOrder
}

export type CompletionStepMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  achievementId?: Prisma.SortOrder
}

export type CompletionStepCreateNestedManyWithoutAchievementInput = {
  create?: Prisma.XOR<Prisma.CompletionStepCreateWithoutAchievementInput, Prisma.CompletionStepUncheckedCreateWithoutAchievementInput> | Prisma.CompletionStepCreateWithoutAchievementInput[] | Prisma.CompletionStepUncheckedCreateWithoutAchievementInput[]
  connectOrCreate?: Prisma.CompletionStepCreateOrConnectWithoutAchievementInput | Prisma.CompletionStepCreateOrConnectWithoutAchievementInput[]
  createMany?: Prisma.CompletionStepCreateManyAchievementInputEnvelope
  connect?: Prisma.CompletionStepWhereUniqueInput | Prisma.CompletionStepWhereUniqueInput[]
}

export type CompletionStepUncheckedCreateNestedManyWithoutAchievementInput = {
  create?: Prisma.XOR<Prisma.CompletionStepCreateWithoutAchievementInput, Prisma.CompletionStepUncheckedCreateWithoutAchievementInput> | Prisma.CompletionStepCreateWithoutAchievementInput[] | Prisma.CompletionStepUncheckedCreateWithoutAchievementInput[]
  connectOrCreate?: Prisma.CompletionStepCreateOrConnectWithoutAchievementInput | Prisma.CompletionStepCreateOrConnectWithoutAchievementInput[]
  createMany?: Prisma.CompletionStepCreateManyAchievementInputEnvelope
  connect?: Prisma.CompletionStepWhereUniqueInput | Prisma.CompletionStepWhereUniqueInput[]
}

export type CompletionStepUpdateManyWithoutAchievementNestedInput = {
  create?: Prisma.XOR<Prisma.CompletionStepCreateWithoutAchievementInput, Prisma.CompletionStepUncheckedCreateWithoutAchievementInput> | Prisma.CompletionStepCreateWithoutAchievementInput[] | Prisma.CompletionStepUncheckedCreateWithoutAchievementInput[]
  connectOrCreate?: Prisma.CompletionStepCreateOrConnectWithoutAchievementInput | Prisma.CompletionStepCreateOrConnectWithoutAchievementInput[]
  upsert?: Prisma.CompletionStepUpsertWithWhereUniqueWithoutAchievementInput | Prisma.CompletionStepUpsertWithWhereUniqueWithoutAchievementInput[]
  createMany?: Prisma.CompletionStepCreateManyAchievementInputEnvelope
  set?: Prisma.CompletionStepWhereUniqueInput | Prisma.CompletionStepWhereUniqueInput[]
  disconnect?: Prisma.CompletionStepWhereUniqueInput | Prisma.CompletionStepWhereUniqueInput[]
  delete?: Prisma.CompletionStepWhereUniqueInput | Prisma.CompletionStepWhereUniqueInput[]
  connect?: Prisma.CompletionStepWhereUniqueInput | Prisma.CompletionStepWhereUniqueInput[]
  update?: Prisma.CompletionStepUpdateWithWhereUniqueWithoutAchievementInput | Prisma.CompletionStepUpdateWithWhereUniqueWithoutAchievementInput[]
  updateMany?: Prisma.CompletionStepUpdateManyWithWhereWithoutAchievementInput | Prisma.CompletionStepUpdateManyWithWhereWithoutAchievementInput[]
  deleteMany?: Prisma.CompletionStepScalarWhereInput | Prisma.CompletionStepScalarWhereInput[]
}

export type CompletionStepUncheckedUpdateManyWithoutAchievementNestedInput = {
  create?: Prisma.XOR<Prisma.CompletionStepCreateWithoutAchievementInput, Prisma.CompletionStepUncheckedCreateWithoutAchievementInput> | Prisma.CompletionStepCreateWithoutAchievementInput[] | Prisma.CompletionStepUncheckedCreateWithoutAchievementInput[]
  connectOrCreate?: Prisma.CompletionStepCreateOrConnectWithoutAchievementInput | Prisma.CompletionStepCreateOrConnectWithoutAchievementInput[]
  upsert?: Prisma.CompletionStepUpsertWithWhereUniqueWithoutAchievementInput | Prisma.CompletionStepUpsertWithWhereUniqueWithoutAchievementInput[]
  createMany?: Prisma.CompletionStepCreateManyAchievementInputEnvelope
  set?: Prisma.CompletionStepWhereUniqueInput | Prisma.CompletionStepWhereUniqueInput[]
  disconnect?: Prisma.CompletionStepWhereUniqueInput | Prisma.CompletionStepWhereUniqueInput[]
  delete?: Prisma.CompletionStepWhereUniqueInput | Prisma.CompletionStepWhereUniqueInput[]
  connect?: Prisma.CompletionStepWhereUniqueInput | Prisma.CompletionStepWhereUniqueInput[]
  update?: Prisma.CompletionStepUpdateWithWhereUniqueWithoutAchievementInput | Prisma.CompletionStepUpdateWithWhereUniqueWithoutAchievementInput[]
  updateMany?: Prisma.CompletionStepUpdateManyWithWhereWithoutAchievementInput | Prisma.CompletionStepUpdateManyWithWhereWithoutAchievementInput[]
  deleteMany?: Prisma.CompletionStepScalarWhereInput | Prisma.CompletionStepScalarWhereInput[]
}

export type CompletionStepCreateWithoutAchievementInput = {
  id?: string
  description?: string | null
  status: boolean
}

export type CompletionStepUncheckedCreateWithoutAchievementInput = {
  id?: string
  description?: string | null
  status: boolean
}

export type CompletionStepCreateOrConnectWithoutAchievementInput = {
  where: Prisma.CompletionStepWhereUniqueInput
  create: Prisma.XOR<Prisma.CompletionStepCreateWithoutAchievementInput, Prisma.CompletionStepUncheckedCreateWithoutAchievementInput>
}

export type CompletionStepCreateManyAchievementInputEnvelope = {
  data: Prisma.CompletionStepCreateManyAchievementInput | Prisma.CompletionStepCreateManyAchievementInput[]
  skipDuplicates?: boolean
}

export type CompletionStepUpsertWithWhereUniqueWithoutAchievementInput = {
  where: Prisma.CompletionStepWhereUniqueInput
  update: Prisma.XOR<Prisma.CompletionStepUpdateWithoutAchievementInput, Prisma.CompletionStepUncheckedUpdateWithoutAchievementInput>
  create: Prisma.XOR<Prisma.CompletionStepCreateWithoutAchievementInput, Prisma.CompletionStepUncheckedCreateWithoutAchievementInput>
}

export type CompletionStepUpdateWithWhereUniqueWithoutAchievementInput = {
  where: Prisma.CompletionStepWhereUniqueInput
  data: Prisma.XOR<Prisma.CompletionStepUpdateWithoutAchievementInput, Prisma.CompletionStepUncheckedUpdateWithoutAchievementInput>
}

export type CompletionStepUpdateManyWithWhereWithoutAchievementInput = {
  where: Prisma.CompletionStepScalarWhereInput
  data: Prisma.XOR<Prisma.CompletionStepUpdateManyMutationInput, Prisma.CompletionStepUncheckedUpdateManyWithoutAchievementInput>
}

export type CompletionStepScalarWhereInput = {
  AND?: Prisma.CompletionStepScalarWhereInput | Prisma.CompletionStepScalarWhereInput[]
  OR?: Prisma.CompletionStepScalarWhereInput[]
  NOT?: Prisma.CompletionStepScalarWhereInput | Prisma.CompletionStepScalarWhereInput[]
  id?: Prisma.StringFilter<"CompletionStep"> | string
  description?: Prisma.StringNullableFilter<"CompletionStep"> | string | null
  status?: Prisma.BoolFilter<"CompletionStep"> | boolean
  achievementId?: Prisma.StringFilter<"CompletionStep"> | string
}

export type CompletionStepCreateManyAchievementInput = {
  id?: string
  description?: string | null
  status: boolean
}

export type CompletionStepUpdateWithoutAchievementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CompletionStepUncheckedUpdateWithoutAchievementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CompletionStepUncheckedUpdateManyWithoutAchievementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type CompletionStepSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  description?: boolean
  status?: boolean
  achievementId?: boolean
  achievement?: boolean | Prisma.AchievementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["completionStep"]>

export type CompletionStepSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  description?: boolean
  status?: boolean
  achievementId?: boolean
  achievement?: boolean | Prisma.AchievementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["completionStep"]>

export type CompletionStepSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  description?: boolean
  status?: boolean
  achievementId?: boolean
  achievement?: boolean | Prisma.AchievementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["completionStep"]>

export type CompletionStepSelectScalar = {
  id?: boolean
  description?: boolean
  status?: boolean
  achievementId?: boolean
}

export type CompletionStepOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "description" | "status" | "achievementId", ExtArgs["result"]["completionStep"]>
export type CompletionStepInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  achievement?: boolean | Prisma.AchievementDefaultArgs<ExtArgs>
}
export type CompletionStepIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  achievement?: boolean | Prisma.AchievementDefaultArgs<ExtArgs>
}
export type CompletionStepIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  achievement?: boolean | Prisma.AchievementDefaultArgs<ExtArgs>
}

export type $CompletionStepPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CompletionStep"
  objects: {
    achievement: Prisma.$AchievementPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    description: string | null
    status: boolean
    achievementId: string
  }, ExtArgs["result"]["completionStep"]>
  composites: {}
}

export type CompletionStepGetPayload<S extends boolean | null | undefined | CompletionStepDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload, S>

export type CompletionStepCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CompletionStepFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CompletionStepCountAggregateInputType | true
  }

export interface CompletionStepDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CompletionStep'], meta: { name: 'CompletionStep' } }
  /**
   * Find zero or one CompletionStep that matches the filter.
   * @param {CompletionStepFindUniqueArgs} args - Arguments to find a CompletionStep
   * @example
   * // Get one CompletionStep
   * const completionStep = await prisma.completionStep.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CompletionStepFindUniqueArgs>(args: Prisma.SelectSubset<T, CompletionStepFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CompletionStepClient<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CompletionStep that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CompletionStepFindUniqueOrThrowArgs} args - Arguments to find a CompletionStep
   * @example
   * // Get one CompletionStep
   * const completionStep = await prisma.completionStep.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CompletionStepFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CompletionStepFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CompletionStepClient<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CompletionStep that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletionStepFindFirstArgs} args - Arguments to find a CompletionStep
   * @example
   * // Get one CompletionStep
   * const completionStep = await prisma.completionStep.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CompletionStepFindFirstArgs>(args?: Prisma.SelectSubset<T, CompletionStepFindFirstArgs<ExtArgs>>): Prisma.Prisma__CompletionStepClient<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CompletionStep that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletionStepFindFirstOrThrowArgs} args - Arguments to find a CompletionStep
   * @example
   * // Get one CompletionStep
   * const completionStep = await prisma.completionStep.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CompletionStepFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CompletionStepFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CompletionStepClient<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CompletionSteps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletionStepFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CompletionSteps
   * const completionSteps = await prisma.completionStep.findMany()
   * 
   * // Get first 10 CompletionSteps
   * const completionSteps = await prisma.completionStep.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const completionStepWithIdOnly = await prisma.completionStep.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CompletionStepFindManyArgs>(args?: Prisma.SelectSubset<T, CompletionStepFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CompletionStep.
   * @param {CompletionStepCreateArgs} args - Arguments to create a CompletionStep.
   * @example
   * // Create one CompletionStep
   * const CompletionStep = await prisma.completionStep.create({
   *   data: {
   *     // ... data to create a CompletionStep
   *   }
   * })
   * 
   */
  create<T extends CompletionStepCreateArgs>(args: Prisma.SelectSubset<T, CompletionStepCreateArgs<ExtArgs>>): Prisma.Prisma__CompletionStepClient<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CompletionSteps.
   * @param {CompletionStepCreateManyArgs} args - Arguments to create many CompletionSteps.
   * @example
   * // Create many CompletionSteps
   * const completionStep = await prisma.completionStep.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CompletionStepCreateManyArgs>(args?: Prisma.SelectSubset<T, CompletionStepCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CompletionSteps and returns the data saved in the database.
   * @param {CompletionStepCreateManyAndReturnArgs} args - Arguments to create many CompletionSteps.
   * @example
   * // Create many CompletionSteps
   * const completionStep = await prisma.completionStep.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CompletionSteps and only return the `id`
   * const completionStepWithIdOnly = await prisma.completionStep.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CompletionStepCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CompletionStepCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CompletionStep.
   * @param {CompletionStepDeleteArgs} args - Arguments to delete one CompletionStep.
   * @example
   * // Delete one CompletionStep
   * const CompletionStep = await prisma.completionStep.delete({
   *   where: {
   *     // ... filter to delete one CompletionStep
   *   }
   * })
   * 
   */
  delete<T extends CompletionStepDeleteArgs>(args: Prisma.SelectSubset<T, CompletionStepDeleteArgs<ExtArgs>>): Prisma.Prisma__CompletionStepClient<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CompletionStep.
   * @param {CompletionStepUpdateArgs} args - Arguments to update one CompletionStep.
   * @example
   * // Update one CompletionStep
   * const completionStep = await prisma.completionStep.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CompletionStepUpdateArgs>(args: Prisma.SelectSubset<T, CompletionStepUpdateArgs<ExtArgs>>): Prisma.Prisma__CompletionStepClient<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CompletionSteps.
   * @param {CompletionStepDeleteManyArgs} args - Arguments to filter CompletionSteps to delete.
   * @example
   * // Delete a few CompletionSteps
   * const { count } = await prisma.completionStep.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CompletionStepDeleteManyArgs>(args?: Prisma.SelectSubset<T, CompletionStepDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CompletionSteps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletionStepUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CompletionSteps
   * const completionStep = await prisma.completionStep.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CompletionStepUpdateManyArgs>(args: Prisma.SelectSubset<T, CompletionStepUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CompletionSteps and returns the data updated in the database.
   * @param {CompletionStepUpdateManyAndReturnArgs} args - Arguments to update many CompletionSteps.
   * @example
   * // Update many CompletionSteps
   * const completionStep = await prisma.completionStep.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CompletionSteps and only return the `id`
   * const completionStepWithIdOnly = await prisma.completionStep.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CompletionStepUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CompletionStepUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CompletionStep.
   * @param {CompletionStepUpsertArgs} args - Arguments to update or create a CompletionStep.
   * @example
   * // Update or create a CompletionStep
   * const completionStep = await prisma.completionStep.upsert({
   *   create: {
   *     // ... data to create a CompletionStep
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CompletionStep we want to update
   *   }
   * })
   */
  upsert<T extends CompletionStepUpsertArgs>(args: Prisma.SelectSubset<T, CompletionStepUpsertArgs<ExtArgs>>): Prisma.Prisma__CompletionStepClient<runtime.Types.Result.GetResult<Prisma.$CompletionStepPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CompletionSteps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletionStepCountArgs} args - Arguments to filter CompletionSteps to count.
   * @example
   * // Count the number of CompletionSteps
   * const count = await prisma.completionStep.count({
   *   where: {
   *     // ... the filter for the CompletionSteps we want to count
   *   }
   * })
  **/
  count<T extends CompletionStepCountArgs>(
    args?: Prisma.Subset<T, CompletionStepCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CompletionStepCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CompletionStep.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletionStepAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CompletionStepAggregateArgs>(args: Prisma.Subset<T, CompletionStepAggregateArgs>): Prisma.PrismaPromise<GetCompletionStepAggregateType<T>>

  /**
   * Group by CompletionStep.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletionStepGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CompletionStepGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CompletionStepGroupByArgs['orderBy'] }
      : { orderBy?: CompletionStepGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CompletionStepGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCompletionStepGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CompletionStep model
 */
readonly fields: CompletionStepFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CompletionStep.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CompletionStepClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  achievement<T extends Prisma.AchievementDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AchievementDefaultArgs<ExtArgs>>): Prisma.Prisma__AchievementClient<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CompletionStep model
 */
export interface CompletionStepFieldRefs {
  readonly id: Prisma.FieldRef<"CompletionStep", 'String'>
  readonly description: Prisma.FieldRef<"CompletionStep", 'String'>
  readonly status: Prisma.FieldRef<"CompletionStep", 'Boolean'>
  readonly achievementId: Prisma.FieldRef<"CompletionStep", 'String'>
}
    

// Custom InputTypes
/**
 * CompletionStep findUnique
 */
export type CompletionStepFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepInclude<ExtArgs> | null
  /**
   * Filter, which CompletionStep to fetch.
   */
  where: Prisma.CompletionStepWhereUniqueInput
}

/**
 * CompletionStep findUniqueOrThrow
 */
export type CompletionStepFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepInclude<ExtArgs> | null
  /**
   * Filter, which CompletionStep to fetch.
   */
  where: Prisma.CompletionStepWhereUniqueInput
}

/**
 * CompletionStep findFirst
 */
export type CompletionStepFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepInclude<ExtArgs> | null
  /**
   * Filter, which CompletionStep to fetch.
   */
  where?: Prisma.CompletionStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CompletionSteps to fetch.
   */
  orderBy?: Prisma.CompletionStepOrderByWithRelationInput | Prisma.CompletionStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CompletionSteps.
   */
  cursor?: Prisma.CompletionStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CompletionSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CompletionSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CompletionSteps.
   */
  distinct?: Prisma.CompletionStepScalarFieldEnum | Prisma.CompletionStepScalarFieldEnum[]
}

/**
 * CompletionStep findFirstOrThrow
 */
export type CompletionStepFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepInclude<ExtArgs> | null
  /**
   * Filter, which CompletionStep to fetch.
   */
  where?: Prisma.CompletionStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CompletionSteps to fetch.
   */
  orderBy?: Prisma.CompletionStepOrderByWithRelationInput | Prisma.CompletionStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CompletionSteps.
   */
  cursor?: Prisma.CompletionStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CompletionSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CompletionSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CompletionSteps.
   */
  distinct?: Prisma.CompletionStepScalarFieldEnum | Prisma.CompletionStepScalarFieldEnum[]
}

/**
 * CompletionStep findMany
 */
export type CompletionStepFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepInclude<ExtArgs> | null
  /**
   * Filter, which CompletionSteps to fetch.
   */
  where?: Prisma.CompletionStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CompletionSteps to fetch.
   */
  orderBy?: Prisma.CompletionStepOrderByWithRelationInput | Prisma.CompletionStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CompletionSteps.
   */
  cursor?: Prisma.CompletionStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CompletionSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CompletionSteps.
   */
  skip?: number
  distinct?: Prisma.CompletionStepScalarFieldEnum | Prisma.CompletionStepScalarFieldEnum[]
}

/**
 * CompletionStep create
 */
export type CompletionStepCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepInclude<ExtArgs> | null
  /**
   * The data needed to create a CompletionStep.
   */
  data: Prisma.XOR<Prisma.CompletionStepCreateInput, Prisma.CompletionStepUncheckedCreateInput>
}

/**
 * CompletionStep createMany
 */
export type CompletionStepCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CompletionSteps.
   */
  data: Prisma.CompletionStepCreateManyInput | Prisma.CompletionStepCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CompletionStep createManyAndReturn
 */
export type CompletionStepCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * The data used to create many CompletionSteps.
   */
  data: Prisma.CompletionStepCreateManyInput | Prisma.CompletionStepCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CompletionStep update
 */
export type CompletionStepUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepInclude<ExtArgs> | null
  /**
   * The data needed to update a CompletionStep.
   */
  data: Prisma.XOR<Prisma.CompletionStepUpdateInput, Prisma.CompletionStepUncheckedUpdateInput>
  /**
   * Choose, which CompletionStep to update.
   */
  where: Prisma.CompletionStepWhereUniqueInput
}

/**
 * CompletionStep updateMany
 */
export type CompletionStepUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CompletionSteps.
   */
  data: Prisma.XOR<Prisma.CompletionStepUpdateManyMutationInput, Prisma.CompletionStepUncheckedUpdateManyInput>
  /**
   * Filter which CompletionSteps to update
   */
  where?: Prisma.CompletionStepWhereInput
  /**
   * Limit how many CompletionSteps to update.
   */
  limit?: number
}

/**
 * CompletionStep updateManyAndReturn
 */
export type CompletionStepUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * The data used to update CompletionSteps.
   */
  data: Prisma.XOR<Prisma.CompletionStepUpdateManyMutationInput, Prisma.CompletionStepUncheckedUpdateManyInput>
  /**
   * Filter which CompletionSteps to update
   */
  where?: Prisma.CompletionStepWhereInput
  /**
   * Limit how many CompletionSteps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CompletionStep upsert
 */
export type CompletionStepUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepInclude<ExtArgs> | null
  /**
   * The filter to search for the CompletionStep to update in case it exists.
   */
  where: Prisma.CompletionStepWhereUniqueInput
  /**
   * In case the CompletionStep found by the `where` argument doesn't exist, create a new CompletionStep with this data.
   */
  create: Prisma.XOR<Prisma.CompletionStepCreateInput, Prisma.CompletionStepUncheckedCreateInput>
  /**
   * In case the CompletionStep was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CompletionStepUpdateInput, Prisma.CompletionStepUncheckedUpdateInput>
}

/**
 * CompletionStep delete
 */
export type CompletionStepDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepInclude<ExtArgs> | null
  /**
   * Filter which CompletionStep to delete.
   */
  where: Prisma.CompletionStepWhereUniqueInput
}

/**
 * CompletionStep deleteMany
 */
export type CompletionStepDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CompletionSteps to delete
   */
  where?: Prisma.CompletionStepWhereInput
  /**
   * Limit how many CompletionSteps to delete.
   */
  limit?: number
}

/**
 * CompletionStep without action
 */
export type CompletionStepDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletionStep
   */
  select?: Prisma.CompletionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletionStep
   */
  omit?: Prisma.CompletionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletionStepInclude<ExtArgs> | null
}
